"""create audit logs table

Revision ID: fe7387f24551
Revises: 395db6469d41
Create Date: 2026-05-12 06:31:10.312985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7387f24551'
down_revision: Union[str, Sequence[str], None] = '395db6469d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column('audit_logs', sa.Column('status_code', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('old_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('new_values', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_logs', 'extra_data')
    op.drop_column('audit_logs', 'new_values')
    op.drop_column('audit_logs', 'old_values')
    op.drop_column('audit_logs', 'description')
    op.drop_column('audit_logs', 'status_code')
    op.drop_column('audit_logs', 'user_agent')
    # ### end Alembic commands ###
