"""add remuneration fields to user contracts

Revision ID: fe8f402ba229
Revises: 0087c371fef4
Create Date: 2026-06-01 02:11:26.552248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8f402ba229'
down_revision: Union[str, Sequence[str], None] = '0087c371fef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_contracts', sa.Column('remuneration_type', sa.String(length=20), nullable=False))
    op.add_column('user_contracts', sa.Column('remuneration_value', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_contracts', 'remuneration_value')
    op.drop_column('user_contracts', 'remuneration_type')
    # ### end Alembic commands ###
